; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;   底座 board：Espressif ESP32-S3-DevKitC-1（官方板）
;   覆盖项：芯片为 ESP32-S3-FH4R2（4MB Flash + 2MB PSRAM + USB CDC）

[env:esp32-s3-fh4r2]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_echo = yes

; ============ 芯片特性覆盖 ============

board_build.partitions = min_spiffs.csv     ; 使用 min_spiffs.csv 分区表
board_upload.maximum_size = 4194304         ; 4 * 1024 * 1024
board_upload.flash_size = 4MB				; Flash 容量

; ============ build_flags ============

build_flags =
    -UARDUINO_USB_MODE                      ; undefine 官方板的 USB_MODE
    -DARDUINO_USB_CDC_ON_BOOT=1             ; 启用 USB CDC 串口
    -DBOARD_HAS_PSRAM                       ; FH4R2 内置 2MB Octal PSRAM


lib_deps = 
	fastled/FastLED @ 3.10.3
	madhephaestus/ESP32Servo@ 3.2.1
